name: prospekt_essens_planer
packages:
  - apps/*
  - packages/*

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    exec: flutter analyze
    description: Run flutter analyze for all packages.
  test:
    exec: flutter test
    description: Run flutter test for all packages.
