name: prospekt_essens_planer
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  prospekt_core:
    path: ../../packages/prospekt_core
  prospekt_data:
    path: ../../packages/prospekt_data
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  file_picker: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shimmer: ^3.0.0
  tutorial_coach_mark: ^1.2.9
  shared_preferences: ^2.2.3

  image_picker: ^1.1.2
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.9
  mockito: ^5.4.4
  riverpod_generator: ^2.4.0
  drift: ^2.32.1

flutter:
  uses-material-design: true
  generate: true
